## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

notifications:
  email: false

git:
  depth: 99999999

jobs:
  allow_failures:
    - julia: nightly
  include:
    - stage: deploy-site
      julia: 1.4
      os: linux
      dist: focal
      if: type != pull_request
      script:
        - julia --project -e 'using Pkg; pkg"build"'
        - mkdir -p book/build
        - julia --project=book -e 'using Pkg; pkg"dev ."; pkg"instantiate"'
        - julia --project=book -e 'ARGS=["build", "images", "html"]; cd("book"); include("make.jl")'
        - julia --project=book deploy.jl
      addons:
        apt_packages:
          - asciidoctor
          - texlive-luatex
          - pdf2svg
          - lmodern
          - fonts-dejavu
          - ttf-ubuntu-font-family
          - texlive-xetex
          - texlive-latex-extra