[[chap08]]
== Cadenas

Las cadenas son diferentes de los números enteros, flotantes y booleanos. Una cadena es una _secuencia_, es decir, es una colección ordenada de valores. En este capítulo veremos cómo acceder a los caracteres que forman una cadena, y conoceremos algunas funciones integradas en Julia relacionadas con cadenas.
(((string)))(((sequence)))

[[characters]]
=== Caracteres

Los hispanohablantes están familiarizados con algunos caracteres, tales como las letras del alfabeto (A, B, C, ...), los números y los signos de puntuación comunes. Estos caracteres están estandarizados en el código _ASCII_ (Código Estándar Estadounidense para el Intercambio de Información).
(((ASCII standard)))

Por supuesto hay muchos otros caracteres utilizados en idiomas distintos del español que no están en el código _ASCII_, tales como aquellos usados en los idiomas griego, árabe, chino, hebreo, hindi, japonés y coreano.

Definir qué es un carácter es altamente complejo. La _norma Unicode_ permite abordar este problema, y se considera como el estándar definitivo para ello. Esta norma funciona asignando un número único para cada carácter a nivel global.
(((Unicode standard)))

Un valor +Char+ representa un único carácter y está entre comillas simples:
(((Char)))((("type", "Base", "Char", see="Char")))

[source,@julia-repl-test]
----
julia> 'x'
'x': ASCII/Unicode U+0078 (category Ll: Letter, lowercase)
julia> '🍌'
'🍌': Unicode U+01f34c (category So: Symbol, other)
julia> typeof('x')
Char
----

Incluso los emojis son parte del estándar Unicode. (*+\:banana: TAB+*)
(((emoji)))


=== Una Cadena es una Secuencia

Una cadena es una secuencia de caracteres. Se puede acceder a un carácter con el operador corchete:
(((string)))(((String)))(((sequence)))(((bracket operator)))((("[]", see="bracket operator")))((("operator", "Base", "[]", see="bracket operator")))

[source,@julia-repl-test chap08]
----
julia> fruta = "banana"
"banana"
julia> letra = fruta[1]
'b': ASCII/Unicode U+0062 (category Ll: Letter, lowercase)
----

La segunda sentencia selecciona el carácter número 1 de +fruta+ y la asigna a la variable +letra+. 

La expresión entre corchetes se llama _indice_. El índice indica el carácter de la secuencia a obtener (de ahí el nombre).
(((index)))

La indexación en Julia es base 1, es decir, el primer elemento de cualquier objeto indexado con enteros está en el índice 1, y el último en el índice +end+:
(((end)))

[source,@julia-repl-test chap08]
----
julia> fruta[end]
'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)
----

Como índice se pueden usar expresiones que contengan variables y operadores:

[source,@julia-repl-test chap08]
----
julia> i = 1
1
julia> fruta[i+1]
'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)
julia> fruta[end-1]
'n': ASCII/Unicode U+006e (category Ll: Letter, lowercase)
----

Pero el valor del índice tiene que ser un número entero. De lo contrario se obtiene:
(((MethodError)))((("error", "Core", "MethodError", see="MethodError")))

[source,@julia-repl-test chap08]
----
julia> letra = fruta[1.5]
ERROR: MethodError: no method matching getindex(::String, ::Float64)
----


=== +length+

+length+ es una función integrada que devuelve el número de caracteres de una cadena:
(((length)))

[source,@julia-repl-test chap08]
----
julia> frutas = "🍌 🍎 🍐"
"🍌 🍎 🍐"
julia> len = length(frutas)
5
----

Para obtener la última letra de una cadena, puede sentirse tentado a probar algo como esto:

[source,@julia-repl-test chap08]
----
julia> last = frutas[len]
' ': ASCII/Unicode U+0020 (category Zs: Separator, space)
----

Pero con esto no se obtiene el resultado esperado.

Las cadenas se codifican usando _codificación UTF-8_. UTF-8 es una codificación de longitud variable, lo que significa que no todos los caracteres están codificados con el mismo número de bytes.
(((UTF-8 encoding)))

La función +sizeof+ devuelve el número de bytes de una cadena:
(((sizeof)))((("function", "Base", "sizeof", see="sizeof")))

[source,@julia-repl-test chap08]
----
julia> sizeof("🍌")
4
----

Dado que un emoji está codificado en 4 bytes y la indexación de cadenas está basada en bytes, el quinto elemento de +frutas+ es un +ESPACIO+.
(((emoji)))

Esto significa que no todos los índices de byte de una cadena UTF-8 son necesariamente índices válidos para un carácter. Si en una cadena se indexa con un índice de bytes no válido, se genera un error:
(((StringIndexError)))((("error", "Base", "StringIndexError", see="StringIndexError")))

[source,@julia-repl-test chap08]
----
julia> frutas[2]
ERROR: StringIndexError("🍌 🍎 🍐", 2)
----

En el caso de +frutas+, el carácter +🍌+ es un carácter de cuatro bytes, por lo que los índices 2, 3 y 4 no son válidos y el índice del siguiente carácter es 5; el siguiente índice válido se puede calcular con +nextind(frutas, 1)+, el subsiguiente con +nextind(frutas,5)+ y así sucesivamente.
(((nextind)))((("function", "Base", "nextind", see="nextind")))


=== Recorrido

Muchos cálculos implican procesar una cadena carácter por carácter. A menudo empiezan por el principio, seleccionan cada carácter por turno, hacen algo con él y continúan hasta el final. Este patrón de proceso se llama _recorrido_. Una forma de escribir un recorrido es con una sentencia while:
(((traversal)))(((while statement)))

[source,@julia-setup chap08]
----
indice = primerindice(frutas)
while indice <= sizeof(frutas)
    letra = frutas[indice]
    println(letra)
    global indice = nextind(frutas, indice)
end
----

Este bucle recorre la cadena y muestra cada letra en una línea distinta. La condición del bucle es +index pass:[&lt;=] sizeof(fruta)+, de modo que cuando el indice es mayor al número de bytes en la cadena, la condición es +falsa+, y no se ejecuta el cuerpo del bucle.

La función +primerindice+ devuelve el primer índice de bytes válido. La palabra reservada +global+ antes de +indice+ indica que queremos reasignar la variable +indice+ definida en +Main+ (ver <<variables_globales>>).
(((global)))(((firstindex)))((("function", "Base", "firstindex", see="firstindex")))

==== Ejercicio 8-1

Escriba una función que tome una cadena como argumento y que muestre las letras desde la última a la primera, una por línea.

Otra forma de escribir un recorrido es con un bucle +for+:
(((for statement)))(((in)))

[source,@julia-setup chap08]
----
for letra in frutas
    println(letra)
end
----

Cada vez que recorremos el bucle, se asigna a la variable +letra+ el siguiente carácter de la cadena. El bucle continúa hasta que no quedan más caracteres.

El ejemplo siguiente muestra cómo usar la concatenación (multiplicación de cadenas) y un bucle for para generar una serie abecedaria (es decir, una serie con elementos en orden alfabético). Por ejemplo, en el libro de Robert McCloskey _Make Way for Ducklings_, los nombres de los patitos son Jack, Kack, Lack, Mack, Nack, Ouack, Pack, y Quack. Este bucle muestra esos nombres en orden:

[source,@julia chap08-3]
----
prefijos = "JKLMNOPQ"
sufijos = "ack"

for letra in prefijos
    println(letra * sufijo)
end
----

Por supuesto, esto no es del todo correcto, porque “Ouack” y “Quack” no están correctamente escritos.

==== Ejercicio 8-2

Modifique este programa para solucionar este error.

=== Porciones de Cadenas

A la subcadena de una cadena se le llama _porción_. La selección de una porción es similar a la selección de un carácter:
(((slice)))

[source,@julia-repl-test chap08]
----
julia> str = "Julio Cesar";

julia> str[1:6]
"Julio"
----

El operador +[n:m]+ devuelve la parte de la cadena desde el +n+-ésimo byte hasta el +m+-ésimo. Por lo tanto, se siguen las mismas reglas que para la indexación simple.
(((bracket operator)))

La palabra reservada +end+ se puede usar para indicar al último byte de la cadena:
(((end)))

[source,@julia-repl-test chap08]
----
julia> str[8:end]
"Cesar"
----

Si el primer índice es mayor que el segundo, el resultado es una _cadena vacía_, representada por dos comillas:
(((empty string)))((("&quot;&quot;", see="empty string")))

[source,@julia-repl-test chap08]
----
julia> str[8:7]
""
----

Una cadena vacía no contiene caracteres y tiene una longitud de 0, pero aparte de eso es igual a cualquier otra cadena.

==== Ejercicio 8-3

Continuando este ejemplo, ¿qué crees que significa +str[:]+? Prueba y verás.

=== Las Cadenas son Inmutables

Es tentador usar el operador +[]+ en el lado izquierdo de una asignación, con la intención de cambiar un carácter en una cadena. Por ejemplo:
(((bracket operator)))(((MethodError)))

[source,@julia-repl-test chap08]
----
julia> saludo = "¡Hola, mundo!"
"¡Hola, mundo!"
julia> saludo[3] = 'J'
ERROR: MethodError: no method matching setindex!(::String, ::Char, ::Int64)
----
Nota del traductor: De acuerdo con la codificación de caracteres en utf-8 ó latin-1, el carácter de exclamación ‘¡’, en la variable saludo ocupa dos posiciones, de ahí que la letra ‘H’ esté localizada en el índice 3.

La razón del error es que las cadenas son _inmutables_, lo que significa que no se puede cambiar una cadena existente. Lo más que puedes hacer es crear una nueva cadena que sea una variación de la original:
(((immutable)))

[source,@julia-repl-test chap08]
----
julia> saludo = "J" * saludo[4:end]
"¡Jola, mundo!"
----

Este ejemplo concatena la apertura del signo de exclamación y una nueva primera letra a una porción de saludo. Esta operación no tiene efecto sobre la cadena original.

=== Interpolación de Cadenas

Construir cadenas usando concatenación puede ser un poco engorroso. Para disminuir la necesidad de las llamadas a +string+ o multiplicaciones repetidas, Julia permite la _interpolación de cadenas_ usando +$+:
(((string interpolation)))((("$", see="string interpolation")))

[source,@julia-repl-test]
----
julia> saludo = "¡Hola"
"Hello"
julia> paraquien = "mundo"
"World"
julia> "$saludo, $(paraquien)!"
"¡Hola, mundo!"
----

Esto es más entendible y conveniente que la concatenación de cadenas: +pass:[saludo * ", " * paraquien * "!"]+

La expresión inmediatamente siguiente a +$+ se toma como la expresión cuyo valor se va a interpolar en la cadena. Por lo tanto, puedes interpolar cualquier expresión en una cadena usando paréntesis:

[source,@julia-repl-test]
----
julia> "1 + 2 = $(1 + 2)"
"1 + 2 = 3"
----

[[searching]]
=== Buscar

¿Qué hace la siguiente función?
(((find)))((("function", "programmer-defined", "find", see="find")))

[source,@julia-setup]
----
function buscar(palabra, letra)
    indice = primerindice(palabra)
    while indice <= sizeof(palabra)
        if palabra[indice] == letra
            return indice
        end
        indice = nextind(palabra, indice)
    end
    -1
end
----

En cierto sentido, la funcion buscar es lo contrario del operador +[]+. En lugar de tomar un índice y extraer el carácter correspondiente, toma un carácter y encuentra el índice donde aparece el carácter. Si el carácter no se encuentra, la función devuelve -1.

Este es el primer ejemplo que hemos visto de una sentencia return dentro de un bucle. Si +palabra[indice] == letra+, la función devuelve inmediatamente el índice, escapando del bucle prematuramente.

Si el carácter no aparece en la cadena, entonces el programa sale del bucle normalmente y devuelve -1.

Este patrón de computación se llama a veces un recorrido _eureka_ porque tan pronto como encontramos lo que buscamos, podemos gritar “¡Eureka! ” y dejar de buscar.
(((search)))

==== Ejercicio 8-4
Para encontrar las posiciones de la segunda o tercera ocurrencia de un carácter en una cadena, podemos modificar la función encuentra, agregando un tercer parámetro para la posición inicial en la cadena de búsqueda:

Modifique la función +buscar+ para que tenga un tercer parámetro: el índice de +palabra+ donde debería comenzar a buscar.

[[looping_and_counting]]
=== Iterando y contando

El siguiente programa cuenta el número de veces que aparece la letra +a+ en una cadena:

[source,@julia-setup]
----
palabra = "banana"
contador = 0
for letra in palabra
    if letra == 'a'
        global contador = contador + 1
    end
end
println(contador)
----

Este programa es otro ejemplo del patrón de computación llamada _conteo_.  La variable +contador+ se inicializa en 0 y se incrementa cada vez que encuentra la letra +a+. Cuando termina el bucle, +contador+ contiene el resultado (el número total de letras +a+).
(((counter)))

==== Ejercicio 8-5

Coloque este código en una función llamada +conteo+, y generalícelo de tal manera que tome como argumentos una cadena y una letra.

Luego, vuelva a escribir la función para que, en vez de revisar toda la cadena, utilice la función +buscar+ de tres parámetros de la sección anterior.

=== Librería con cadenas

Julia tiene funciones integradas que realizan una variedad de operaciones útiles en cadenas. Por ejemplo, la función +uppercase+ toma una cadena y devuelve una nueva cadena con todas las letras mayúsculas.
(((uppercase)))((("function", "Base", "uppercase", see="uppercase")))

[source,@julia-repl-test]
----
julia> uppercase("¡Hola, mundo!")
"¡HOLA, MUNDO!"
----

Existe una función llamada +findfirst+ que es notablemente similar a la función +buscar+ que escribimos:
(((findfirst)))((("function", "programmer-defined", "findfirst", see="findfirst")))

[source,@julia-repl-test]
----
julia> findfirst("a", "banana")
2:2
----

La función +findfirst+ es más general que nuestra función; puede encontrar subcadenas, no solo caracteres:

[source,@julia-repl-test]
----
julia> findfirst("na", "banana")
3:4
----

Por defecto, +findfirst+ comienza la búsqueda al comienzo de la cadena, pero la función +findnext+ toma un tercer argumento: el +indice+ donde debería comenzar:
(((findnext)))((("function", "programmer-defined", "findnext", see="findnext")))

[source,@julia-repl-test]
----
julia> findnext("na", "banana", 4)
5:6
----


===  El operador +∈+

El operador +∈+ (*+\in TAB+*) es un operador booleano que toma un carácter y una cadena, y devuelve +true+ si el primero aparece en el segundo:
((("∈", see="in")))((("operator", "Base", "in", see="in")))((("operator", "Base", "∈", see="in")))

[source,@julia-repl-test]
----
julia> 'a' ∈ "banana"    # 'a' en "banana"
true
----

Por ejemplo, la siguiente función imprime todas las letras de palabra1 que también aparecen en palabra2:
(((inboth)))((("function", "programmer-defined", "inboth", see="inboth")))

[source,@julia-setup chap08-2]
----
function ambas(palabra1, palabra2)
    for letra in palabra1
        if letra ∈ palabra2
            print(letra, " ")
        end
    end
end
----

Una  buena elección de nombres de variables permite que Julia se pueda leer como el español. Este bucle puede leerse como: "para (cada) letra en (la primera) palabra, si (la) letra es un elemento de (la segunda) palabra, imprima (la) letra".

Esto es lo que se obtiene si se compara +"manzanas"+ y +"naranjas"+:

[source,@julia-repl-test chap08-2]
----
julia> ambas("manzanas", "naranjas")
a n a n a s
----


=== Comparación de Cadenas

Los operadores de comparación trabajan sobre cadenas. Para ver si dos cadenas son iguales:
(((string comparison)))(((==)))

[source,@julia-setup chap08]
----
palabra = "Piña"
if palabra == "banana"
    println("¡Tenemos bananas!")
end
----

Otras operaciones de comparación son útiles para poner palabras en orden alfabético:
(((alphabetical order)))

[source,@julia-setup chap08]
----
if palabra < "banana"
    println("Su palabra, $word, va antes de banana.")
elseif word > "banana"
    println("Su palabra, $word, va antes de banana.")
else
    println("¡Tenemos bananas!")
end
----

Julia no maneja las letras mayúsculas y minúsculas como lo hace la gente. Todas las letras mayúsculas van antes de las letras minúsculas. Por lo tanto:

[source,@julia-eval chap08]
----
Su palabra, Piña, va antes de banana.
----

[TIP]
====

Una forma común de abordar este problema es convertir las cadenas a un formato estándar, como pueden ser las minúsculas, antes de realizar la comparación. 

====


[[deb08]]
=== Depuración

Cuando se usan índices para recorrer los valores en una secuencia, es difícil acceder al principio y al final del recorrido. Aquí hay una función que compara dos palabras y devuelve +true+ si una de las palabras es el reverso de la otra, pero contiene dos errores:
(((debugging)))(((traversal)))(((isreverse)))((("function", "programmer-defined", "isreverse", see="isreverse")))

[source,@julia-setup chap08]
----
function esreverso(palabra1, palabra2)
    if length(palabra1) != length(palabra2)
        return false
    end
    i = firstindex(palabra1)
    j = lastindex(palabra2)
    while j >= 0
        j = prevind(palabra2, j)
        if palabra1[i] != palabra2[j]
            return false
        end
        i = nextind(palabra1, i)
    end
    true
end
----

La primera sentencia +if+ verifica si las palabras tienen la misma longitud. Si no, se devuelve +false+ inmediatamente. De lo contrario, para el resto de la función, podemos suponer que las palabras tienen la misma longitud. Este es un ejemplo del patrón guardián.

+i+ y +j+ son índices: +i+ recorre +palabra1+ hacia adelante mientras que +j+ recorre +palabra2+ hacia atrás. Si dos letras no coinciden, se devuelve +false+ inmediatamente. Si el ciclo termina y todas las letras coinciden, se devuelve +true+.

La función +lastindex+ devuelve el último índice de bytes válido de una cadena y +prevind+ el índice válido anterior a un carácter.

Si probamos esta función con las palabras "amor" y "roma", esperamos el valor de retorno +true+, pero obtenemos +false+:

[source,@julia-repl-test chap08]
----
julia> esreverso("amor", "roma")
false
----

Para depurar este tipo de error, primeramente imprimamos los valores de los índices:

[source,julia]
----
    while j >= 0
        j = prevind(palabra2, j)
        @show i j
        if palabra1[i] != palabra2[j]
----

[source,@julia-eval chap08]
----
function esreverso(palabra1, palabra2)
    if length(palabra1) != length(palabra2)
        return false
    end
    i = firstindex(palabra1)
    j = lastindex(palabra2)
    while j >= 0
        j = prevind(palabra2, j)
        @show i j
        if palabra1[i] != palabra2[j]
            return false
        end
        i = nextind(palabra1, i)
    end
    true
end;
----

Ahora, al ejecutar el programa, se obtiene más información:

[source,@julia-repl-test chap08]
----
julia> esreverso("amor", "roma")
i = 1 
j = 3
false
----

En la primera iteración del bucle, el valor de +j+ es 3, pero tendría que ser 4. Esto se puede solucionar trasladando la línea +j = prevind (palabra2, j)+ al final del ciclo +while+.

Si se soluciona ese error y se ejecuta el programa nuevamente, se obtiene:

[source,@julia-eval chap08]
----
function esreverso(palabra1, palabra2)
    if length(palabra1) != length(palabra2)
        return false
    end
    i = firstindex(palabra1)
    j = lastindex(palabra2)
    while j >= 0
        @show i j
        if palabra1[i] != palabra2[j]
            return false
        end
        i = nextind(palabra1, i)
        j = prevind(palabra2, j)
    end
    true
end;
----

[source,@julia-repl-test chap08]
----
julia> esreverso("amor", "roma")
i = 1
j = 4
i = 2
j = 3
i = 3
j = 2
i = 4
j = 1
i = 5
j = 0
ERROR: BoundsError: attempt to access "amor"
  at index [5]
----

Esta vez se ha producido un + BoundsError +. El valor de + i + es 5, que está fuera del rango de la cadena + "potes" +.
This time a +BoundsError+ has been thrown. The value of +i+ is 5, which is out a range for the string +"pots"+.
(((BoundsError)))((("error", "Core", "BoundsError", see="BoundsError")))

==== Exercise 8-6

Run the program on paper, changing the values of +i+ and +j+ during each iteration. Find and fix the second error in this function.


=== Glossary

sequence::
An ordered collection of values where each value is identified by an integer index.
(((sequence)))

ASCII standard::
A character encoding standard for electronic communication specifying 128 characters.
(((ASCII standard)))

Unicode standard::
A computing industry standard for the consistent encoding, representation, and handling of text expressed in most of the world's writing systems.
(((Unicode standard)))

index::
An integer value used to select an item in a sequence, such as a character in a string. In Julia indices start from 1.
(((index)))

UTF-8 encoding::
A variable width character encoding capable of encoding all 1112064 valid code points in Unicode using one to four 8-bit bytes.
(((UTF-8 encoding)))

traverse::
To iterate through the items in a sequence, performing a similar operation on each.
(((traversal)))

slice::
A part of a string specified by a range of indices.
(((slice)))

empty string::
A string with no characters and length 0, represented by two quotation marks.
(((empty string)))

immutable::
The property of a sequence whose items cannot be changed.
(((immutable)))

string interpolation::
The process of evaluating a string containing one or more placeholders, yielding a result in which the placeholders are replaced with their corresponding values.
(((string interpolation)))

search::
A pattern of traversal that stops when it finds what it is looking for.
(((search)))

counter::
A variable used to count something, usually initialized to zero and then incremented.
(((counter)))


=== Exercises

[[ex08-1]]
==== Exercise 8-7

Read the documentation of the string functions at https://docs.julialang.org/en/v1/manual/strings/. You might want to experiment with some of them to make sure you understand how they work. +strip+ and +replace+ are particularly useful.

The documentation uses a syntax that might be confusing. For example, in +search(string::AbstractString, chars::Chars, [start::Integer])+, the brackets indicate optional arguments. So +string+ and +chars+ are required, but +start+ is optional.
(((search)))((("function", "Base", "search", see="search")))

[[ex08-2]]
==== Exercise 8-8

There is a built-in function called +count+ that is similar to the function in <<looping_and_counting>>. Read the documentation of this function and use it to count the number of +a+’s in "banana".
(((count)))((("function","Base", "count", see="count")))

[[ex08-3]]
==== Exercise 8-9

A string slice can take a third index. The first specifies the start, the third the end and the second the “step size”; that is, the number of spaces between successive characters. A step size of 2 means every other character; 3 means every third, etc.
(((slice)))

[source,@julia-repl-test]
----
julia> fruit = "banana"
"banana"
julia> fruit[1:2:6]
"bnn"
----

A step size of -1 goes through the word backwards, so the slice +[end:-1:1]+ generates a reversed string.

Use this idiom to write a one-line version of +ispalindrome+ from <<ex06-3>>.
(((ispalindrome)))

[[ex08-4]]
==== Exercise 8-10

The following functions are all _intended_ to check whether a string contains any lowercase letters, but at least some of them are wrong. For each function, describe what the function actually does (assuming that the parameter is a string).

[source,@julia-setup]
----
function anylowercase1(s)
    for c in s
        if islowercase(c)
            return true
        else
            return false
        end
    end
end

function anylowercase2(s)
    for c in s
        if islowercase('c')
            return "true"
        else
            return "false"
        end
    end
end

function anylowercase3(s)
    for c in s
        flag = islowercase(c)
    end
    flag
end

function anylowercase4(s)
    flag = false
    for c in s
        flag = flag || islowercase(c)
    end
    flag
end

function anylowercase5(s)
    for c in s
        if !islowercase(c)
            return false
        end
    end
    true
end
----

[[ex08-5]]
==== Exercise 8-11

A Caesar cypher is a weak form of encryption that involves “rotating” each letter by a fixed number of places. To rotate a letter means to shift it through the alphabet, wrapping around to the beginning if necessary, so +’A’+ rotated by 3 is +’D’+ and +’Z’+ rotated by 1 is +’A’+.
(((Caesar cypher)))

To rotate a word, rotate each letter by the same amount. For example, +"cheer"+ rotated by 7 is +"jolly"+ and +"melon"+ rotated by -10 is +"cubed"+. In the movie _2001: A Space Odyssey, the ship computer_ is called HAL, which is IBM rotated by -1.

Write a function called +rotateword+ that takes a string and an integer as parameters, and returns a new string that contains the letters from the original string rotated by the given amount.
(((rotateword)))((("function","programmer-defined", "rotateword", see="rotateword")))

[TIP]
====
You might want to use the built-in function +Int+, which converts a character to a numeric code, and +Char+, which converts numeric codes to characters. Letters of the alphabet are encoded in alphabetical order, so for example:
(((Int)))(((Char)))

[source,@julia-repl-test]
----
julia> Int('c') - Int('a')
2
----

Because +'c'+ is the third letter of the alphabet. But beware: the numeric codes for uppercase letters are different.

[source,@julia-repl-test]
----
julia> Char(Int('A') + 32)
'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)
----
====

Potentially offensive jokes on the Internet are sometimes encoded in ROT13, which is a Caesar cypher with rotation 13. If you are not easily offended, find and decode some of them.
