[[chap08]]
== Cadenas

Las cadenas son diferentes de los números enteros, flotantes y booleanos. Una cadena es una _secuencia_, es decir, una colección ordenada de valores. En este capítulo se verá cómo acceder a los caracteres que forman una cadena y se conocerán algunas funciones integradas en Julia relacionadas con cadenas.
(((cadena)))(((secuencia)))

[[caracteres]]
=== Caracteres

Los hispanohablantes están familiarizados con algunos caracteres, tales como las letras del alfabeto (A, B, C, ...), los números y los signos de puntuación comunes. Estos caracteres están estandarizados en el código _ASCII_ (Código Estándar Estadounidense para el Intercambio de Información).
(((código ASCII)))

Por supuesto hay muchos otros caracteres utilizados en idiomas distintos del español que no están en el código _ASCII_, tales como aquellos usados en los idiomas griego, árabe, chino, hebreo, hindi, japonés y coreano.

Definir qué es un carácter es altamente complejo. La _norma Unicode_ permite abordar este problema, y se considera como el estándar definitivo para ello. Esta norma funciona asignando un número único para cada carácter a nivel global.
(((norma Unicode)))

Un valor +Char+ representa un único carácter y está entre comillas simples:
(((Char)))((("tipo", "Base", "Char", véase "Char")))

[source,@julia-repl-test]
----
julia> 'x'
'x': ASCII/Unicode U+0078 (category Ll: Letter, lowercase)
julia> '🍌'
'🍌': Unicode U+1F34C (category So: Symbol, other)
julia> typeof('x')
Char
----

Incluso los emojis son parte del estándar Unicode. (*+\:banana: TAB+*)
(((emoji)))


=== Una Cadena es una Secuencia

Una cadena es una secuencia de caracteres. Se puede acceder a un carácter con el operador corchete:
(((cadena)))(((String)))(((secuencia)))(((operador corchete)))((("[]", véase "operador corchete")))((("operador", "Base", "[]", véase "operador corchete")))

[source,@julia-repl-test chap08]
----
julia> fruta = "banana"
"banana"
julia> letra = fruta[1]
'b': ASCII/Unicode U+0062 (category Ll: Letter, lowercase)
----

La segunda sentencia selecciona el carácter número 1 de +fruta+ y la asigna a la variable +letra+. 

La expresión entre corchetes se llama _indice_. El índice indica el carácter de la secuencia a obtener (de ahí el nombre).
(((indice)))

La indexación en Julia es base 1, es decir, el primer elemento de cualquier objeto indexado con enteros está en el índice 1, y el último en el índice +end+:
(((end)))

[source,@julia-repl-test chap08]
----
julia> fruta[end]
'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)
----

Como índice se pueden usar expresiones que contengan variables y operadores:

[source,@julia-repl-test chap08]
----
julia> i = 1
1
julia> fruta[i+1]
'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)
julia> fruta[end-1]
'n': ASCII/Unicode U+006E (category Ll: Letter, lowercase)
----

No obstante, el valor del índice tiene que ser un número entero. De lo contrario se obtiene:
(((MethodError)))((("error", "Core", "MethodError", véase "MethodError")))

[source,@julia-repl-test chap08]
----
julia> letra = fruta[1.5]
ERROR: MethodError: no method matching getindex(::String, ::Float64)
----


=== +length+

+length+ es una función integrada que devuelve el número de caracteres de una cadena:
(((length)))

[source,@julia-repl-test chap08]
----
julia> frutas = "🍌 🍎 🍐"
"🍌 🍎 🍐"
julia> len = length(frutas)
5
----

Para obtener la última letra de una cadena, puede sentirse tentado a probar algo como esto:

[source,@julia-repl-test chap08]
----
julia> last = frutas[len]
' ': ASCII/Unicode U+0020 (category Zs: Separator, space)
----

Pero con esto no se obtiene el resultado esperado.

Las cadenas se codifican usando _codificación UTF-8_. UTF-8 es una codificación de longitud variable, lo que significa que no todos los caracteres están codificados con el mismo número de bytes.
(((codificación UTF-8)))

La función +sizeof+ devuelve el número de bytes de una cadena:
(((sizeof)))((("función", "Base", "sizeof", véase "sizeof")))

[source,@julia-repl-test chap08]
----
julia> sizeof("🍌")
4
----

Dado que un emoji está codificado en 4 bytes y la indexación de cadenas está basada en bytes, el quinto elemento de +frutas+ es un +ESPACIO+.
(((emoji)))

Esto significa que no todos los índices de byte de una cadena UTF-8 son necesariamente índices válidos para un carácter. Si en una cadena se indexa con un índice de bytes no válido, se genera un error:
(((StringIndexError)))((("error", "Base", "StringIndexError", véase "StringIndexError")))

[source,@julia-repl-test chap08]
----
julia> frutas[2]
ERROR: StringIndexError("🍌 🍎 🍐", 2)
----

En el caso de +frutas+, el carácter +🍌+ es un carácter de cuatro bytes, por lo que los índices 2, 3 y 4 no son válidos y el índice del siguiente carácter es 5, el siguiente índice válido se puede calcular con +nextind(frutas, 1)+, el subsiguiente con +nextind(frutas,5)+ y así sucesivamente.
(((nextind)))((("función", "Base", "nextind", véase "nextind")))


=== Recorrido

Muchos cálculos implican procesar una cadena carácter por carácter. A menudo empiezan por el principio, seleccionan cada carácter por turno, hacen algo con él y continúan hasta el final. Este patrón de proceso se llama _recorrido_. Una forma de escribir un recorrido es con una sentencia while:
(((recorrido)))(((sentencia while)))

[source,@julia-setup chap08]
----
indice = firstindex(frutas)
while indice <= sizeof(frutas)
    letra = frutas[indice]
    println(letra)
    global indice = nextind(frutas, indice)
end
----

Este bucle recorre la cadena y muestra cada letra en una línea distinta. La condición del bucle es +index pass:[&lt;=] sizeof(fruta)+, de modo que cuando el índice es mayor al número de bytes en la cadena, la condición es +falsa+ y no se ejecuta el cuerpo del bucle.

La función +firstindex+ devuelve el primer índice de bytes válido. La palabra reservada +global+ antes de +indice+ indica que queremos reasignar la variable +indice+ definida en +Main+ (ver <<variables_globales>>).
(((global)))(((firstindex)))((("función", "Base", "firstindex", véase "firstindex")))

==== Ejercicio 8-1

Escriba una función que tome una cadena como argumento y que muestre las letras desde la última a la primera, una por línea.

Otra forma de escribir un recorrido es con un bucle +for+:
(((sentencia for)))(((in)))

[source,@julia-setup chap08]
----
for letra in frutas
    println(letra)
end
----

Cada vez que se recorre el bucle, se asigna a la variable +letra+ el siguiente carácter de la cadena. El bucle continúa hasta que no quedan más caracteres.

El ejemplo siguiente muestra cómo usar la concatenación (multiplicación de cadenas) y un bucle for para generar una serie abecedaria (es decir, una serie con elementos en orden alfabético). Por ejemplo, en el libro de Robert McCloskey _Make Way for Ducklings_, los nombres de los patitos son Jack, Kack, Lack, Mack, Nack, Ouack, Pack, y Quack. Este bucle muestra esos nombres en orden:

[source,@julia chap08-3]
----
prefijos = "JKLMNOPQ"
sufijo = "ack"

for letra in prefijos
    println(letra * sufijo)
end
----

Por supuesto, esto no es del todo correcto, porque “Ouack” y “Quack” no están correctamente escritos.

==== Ejercicio 8-2

Modifique este programa para solucionar este error.

=== Porciones de Cadenas

A la subcadena de una cadena se le llama _porción_. La selección de una porción es similar a la selección de un carácter:
(((slice)))

[source,@julia-repl-test chap08]
----
julia> str = "Julio Cesar";

julia> str[1:5]
"Julio"
----

El operador +[n:m]+ devuelve la parte de la cadena desde el +n+-ésimo byte hasta el +m+-ésimo. Por lo tanto, se siguen las mismas reglas que para la indexación simple.
(((operador corchete)))

La palabra reservada +end+ se puede usar para indicar al último byte de la cadena:
(((end)))

[source,@julia-repl-test chap08]
----
julia> str[7:end]
"Cesar"
----

Si el primer índice es mayor que el segundo, el resultado es una _cadena vacía_, representada por dos comillas:
(((cadena vacía)))((("&quot;&quot;", véase "cadena vacía")))

[source,@julia-repl-test chap08]
----
julia> str[8:7]
""
----

Una cadena vacía no contiene caracteres y tiene una longitud de 0, pero aparte de eso es igual a cualquier otra cadena.

==== Ejercicio 8-3

Continuando este ejemplo, ¿qué cree que significa +str[:]+? Pruebe y verá.

=== Las Cadenas son Inmutables

Es tentador usar el operador +[]+ en el lado izquierdo de una asignación con la intención de cambiar un carácter en una cadena. Por ejemplo:
(((operador corchete)))(((MethodError)))

[source,@julia-repl-test chap08]
----
julia> saludo = "¡Hola, mundo!"
"¡Hola, mundo!"
julia> saludo[3] = 'J'
ERROR: MethodError: no method matching setindex!(::String, ::Char, ::Int64)
----
Nota del traductor: De acuerdo con la codificación de caracteres en utf-8 o latin-1, el carácter de exclamación ‘¡’, en la variable saludo ocupa dos posiciones, de ahí que la letra ‘H’ esté localizada en el índice 3.

La razón del error es que las cadenas son _inmutables_, lo que significa que no se puede cambiar una cadena existente. Lo máximo que se puede hacer es crear una nueva cadena que sea una variación de la original:
(((immutable)))

[source,@julia-repl-test chap08]
----
julia> saludo = "¡J" * saludo[4:end]
"¡Jola, mundo!"
----

Este ejemplo concatena la apertura del signo de exclamación y una nueva primera letra a una porción de saludo. Esta operación no tiene efecto sobre la cadena original.

=== Interpolación de Cadenas

Construir cadenas usando concatenación puede ser un poco engorroso. Para disminuir la necesidad de las llamadas a +string+ o multiplicaciones repetidas, Julia permite la _interpolación de cadenas_ usando +$+:
(((interpolación de cadenas)))((("$", véase "interpolación de cadenas")))

[source,@julia-repl-test]
----
julia> saludo = "¡Hola"
"¡Hola"
julia> paraquien = "mundo"
"mundo"
julia> "$saludo, $(paraquien)!"
"¡Hola, mundo!"
----

Esto es más entendible y conveniente que la concatenación de cadenas: +pass:[saludo * ", " * paraquien * "!"]+

La expresión inmediatamente siguiente a +$+ se toma como la expresión cuyo valor se va a interpolar en la cadena. Por lo tanto, puede interpolar cualquier expresión en una cadena usando paréntesis:

[source,@julia-repl-test]
----
julia> "1 + 2 = $(1 + 2)"
"1 + 2 = 3"
----

[[searching]]
=== Búsqueda

¿Qué hace la siguiente función?
(((búsqueda)))((("función", "definida por el programador", "búsqueda", véase "búsqueda")))

[source,@julia-setup]
----
function busqueda(palabra, letra)
    indice = primerindice(palabra)
    while indice <= sizeof(palabra)
        if palabra[indice] == letra
            return indice
        end
        indice = nextind(palabra, indice)
    end
    -1
end
----

En cierto sentido, la función búsqueda es lo contrario del operador +[]+. En lugar de tomar un índice y extraer el carácter correspondiente, toma un carácter y encuentra el índice donde aparece el carácter. Si el carácter no se encuentra, la función devuelve -1.

Este es el primer ejemplo de una sentencia return dentro de un bucle. Si +palabra[indice] == letra+, la función devuelve inmediatamente el índice, escapando del bucle prematuramente.

Si el carácter no aparece en la cadena, entonces el programa sale del bucle normalmente y devuelve -1.

Este patrón de computación se llama a veces un recorrido _eureka_ porque tan pronto como encontramos lo que buscamos, podemos gritar “¡Eureka! ” y dejar de buscar.
(((búsqueda)))

==== Ejercicio 8-4

Modifique la función +busqueda+ para que tenga un tercer parámetro: el índice de +palabra+ donde debería comenzar a buscar.

[[looping_and_counting]]
=== Iterando y contando

El siguiente programa cuenta el número de veces que aparece la letra +a+ en una cadena:

[source,@julia-setup]
----
palabra = "banana"
contador = 0
for letra in palabra
    if letra == 'a'
        global contador = contador + 1
    end
end
println(contador)
----

Este programa es otro ejemplo del patrón de computación llamado _conteo_.  La variable +contador+ se inicializa en 0 y se incrementa cada vez que encuentra la letra +a+. Cuando termina el bucle, +contador+ contiene el resultado (el número total de letras +a+).
(((contador)))

==== Ejercicio 8-5

Coloque este código en una función llamada +conteo+, y generalícelo de tal manera que tome como argumentos una cadena y una letra.

Luego, vuelva a escribir la función para que, en vez de revisar toda la cadena, utilice la función +busqueda+ de tres parámetros de la sección anterior.

=== Librería con cadenas

Julia tiene funciones integradas que realizan una variedad de operaciones útiles en cadenas. Por ejemplo, la función +uppercase+ toma una cadena y devuelve una nueva cadena con todas las letras mayúsculas.
(((uppercase)))((("función", "Base", "uppercase", véase "uppercase")))

[source,@julia-repl-test]
----
julia> uppercase("¡Hola, mundo!")
"¡HOLA, MUNDO!"
----

Existe una función llamada +findfirst+ que es notablemente similar a la función +busqueda+ que escribimos:
(((findfirst)))((("función", "definida por el programador", "findfirst", véase "findfirst")))

[source,@julia-repl-test]
----
julia> findfirst("a", "banana")
2:2
----

La función +findfirst+ es más general que la función creada: puede encontrar subcadenas, no solo caracteres:

[source,@julia-repl-test]
----
julia> findfirst("na", "banana")
3:4
----

Por defecto, +findfirst+ empieza la búsqueda al comienzo de la cadena pero la función +findnext+ toma un tercer argumento: el +indice+ donde debería comenzar:
(((findnext)))((("función", "definida por el programador", "findnext", véase "findnext")))

[source,@julia-repl-test]
----
julia> findnext("na", "banana", 4)
5:6
----


===  El operador +∈+

El operador +∈+ (*+\in TAB+*) es un operador booleano que toma un carácter y una cadena, y devuelve +true+ si el primero aparece en el segundo:
((("∈", véase "in")))((("operador", "Base", "in", véase "in")))((("operador", "Base", "∈", véase "in")))

[source,@julia-repl-test]
----
julia> 'a' ∈ "banana"    # 'a' en "banana"
true
----

Por ejemplo, la siguiente función imprime todas las letras de palabra1 que también aparecen en palabra2:
(((ambas)))((("función", "definida por el programador", "ambas", véase "ambas")))

[source,@julia-setup chap08-2]
----
function ambas(palabra1, palabra2)
    for letra in palabra1
        if letra ∈ palabra2
            print(letra, " ")
        end
    end
end
----

Una  buena elección de nombres de variables permite que Julia se pueda leer como el español. Este bucle puede leerse como: "para (cada) letra en (la primera) palabra, si (la) letra es un elemento de (la segunda) palabra, imprima (la) letra".

Esto es lo que se obtiene si se compara +"manzanas"+ y +"naranjas"+:

[source,@julia-repl-test chap08-2]
----
julia> ambas("manzanas", "naranjas")
a n a n a s
----


=== Comparación de Cadenas

Los operadores de comparación trabajan sobre cadenas. Para ver si dos cadenas son iguales:
(((comparación de cadenas)))(((==)))

[source,@julia-setup chap08]
----
palabra = "Piña"
if palabra == "banana"
    println("¡Tenemos bananas!")
end
----

Otras operaciones de comparación son útiles para ordenar alfabéticamente palabras:
(((orden alfabético)))

[source,@julia-setup chap08]
----
if palabra < "banana"
    println("Su palabra, $palabra, va antes de banana.")
elseif word > "banana"
    println("Su palabra, $palabra, va antes de banana.")
else
    println("¡Tenemos bananas!")
end
----

// Pamela, I'm not sure what's going on in the following. Do you really want this?
// Laura: I've rewritten the below paragraph so that it's easier to understand. What do you think?

Julia no maneja las letras mayúsculas y minúsculas del mismo modo que son manejadas en cualquier lengua hablada. Todas las letras mayúsculas van antes de las letras minúsculas, según el estándar de codificación. Por lo tanto:

[source,julia chap08]
----
"Su palabra, Piña, va antes de banana."
----

[TIP]
====

Una forma común de abordar este problema es convertir las cadenas a un formato estándar, como por ejemplo a minúsculas, antes de realizar la comparación. 

====


[[deb08]]
=== Depuración

Cuando se usan índices para recorrer los valores en una secuencia, es difícil acceder al principio y al final del recorrido. Aquí hay una función que compara dos palabras y devuelve +true+ si una de las palabras es el reverso de la otra, pero contiene dos errores:
(((depuración)))(((recorrido)))(((esreverso)))((("función", "definida por el programador", "esreverso", véase "esreverso")))

[source,@julia-setup chap08]
----
function espalindroma(palabra1, palabra2)
    if length(palabra1) != length(palabra2)
        return false
    end
    i = firstindex(palabra1)
    j = lastindex(palabra2)
    while j >= 0
        j = prevind(palabra2, j)
        if palabra1[i] != palabra2[j]
            return false
        end
        i = nextind(palabra1, i)
    end
    true
end
----

La primera sentencia +if+ verifica si las palabras tienen la misma longitud. Si no, se devuelve +false+ inmediatamente. De lo contrario, para el resto de la función, se puede suponer que las palabras tienen la misma longitud. Este es un ejemplo del patrón guardián.

+i+ y +j+ son índices: +i+ recorre +palabra1+ de derecha a izquierda mientras que +j+ recorre +palabra2+ de izquierda a derecha. Si dos letras no coinciden, se devuelve +false+ inmediatamente. Si el ciclo termina y todas las letras coinciden, se devuelve +true+.

La función +lastindex+ devuelve el último índice de bytes válido de una cadena y +prevind+ el índice válido anterior a un carácter.

Si se prueba esta función con las palabras "amor" y "roma", se espera el valor de retorno +true+, pero se obtiene +false+:

[source,@julia-repl-test chap08]
----
julia> espalindroma("amor", "roma")
false
----

Para depurar este tipo de error, primeramente se imprimen los valores de los índices:

// [source,julia]
// ----
//     while j >= 0
//         j = prevind(palabra2, j)
//         @show i j
//         if palabra1[i] != palabra2[j]
// ----

[source,@julia-eval chap08]
----
function espalindroma(palabra1, palabra2)
    if length(palabra1) != length(palabra2)
        return false
    end
    i = firstindex(palabra1)
    j = lastindex(palabra2)
    while j >= 0
        j = prevind(palabra2, j)
        @show i j
        if palabra1[i] != palabra2[j]
            return false
        end
        i = nextind(palabra1, i)
    end
    true
end;
----

Ahora, al ejecutar el programa, se obtiene más información:

[source,@julia-repl-test chap08]
----
julia> espalindroma("amor", "roma")
i = 1 
j = 3
false
----

En la primera iteración del bucle, el valor de +j+ es 3, pero tendría que ser 4. Esto se puede solucionar trasladando la línea +j = prevind (palabra2, j)+ al final del ciclo +while+.

Si se soluciona ese error y se ejecuta el programa nuevamente, se obtiene:

[source,@julia-eval chap08]
----
function espalindroma(palabra1, palabra2)
    if length(palabra1) != length(palabra2)
        return false
    end
    i = firstindex(palabra1)
    j = lastindex(palabra2)
    while j >= 0
        @show i j
        if palabra1[i] != palabra2[j]
            return false
        end
        i = nextind(palabra1, i)
        j = prevind(palabra2, j)
    end
    true
end;
----

[source,@julia-repl-test chap08]
----
julia> espalindroma("amor", "roma")
i = 1
j = 4
i = 2
j = 3
i = 3
j = 2
i = 4
j = 1
i = 5
j = 0
ERROR: BoundsError: attempt to access String
  at index [5]
----

Esta vez se ha producido un +BoundsError+. El valor de +i+ es 5, que está fuera del rango de la cadena +"amor"+.
(((BoundsError)))((("error", "Core", "BoundsError", véase "BoundsError")))

==== Ejercicio 8-6

Ejecute el programa en papel cambiando los valores de +i+ y +j+ durante cada iteración. Encuentre y arregle el segundo error en esta función.

=== Glosario

secuencia::
Una colección ordenada de valores donde cada valor se identifica mediante un índice entero.
(((secuencia)))

código ASCII::
Código de caracteres estándar para el intercambio de información.
(((código ASCII)))

norma Unicode::
Un estándar en la industria informática para la codificación, representación y manejo consistentes de texto en la mayoría de los sistemas de escritura del mundo.
(((norma Unicode)))

índice::
Un valor entero usado para seleccionar un miembro de un conjunto ordenado, como puede ser un carácter de una cadena. En Julia los índices comienzan en 1.
(((índice)))

codificación UTF-8::
Una codificación de caracteres de longitud variable capaz de codificar todos los 1112064 puntos de código válidos en Unicode utilizando de uno a cuatro bytes de 8 bits.
(((codificación UTF-8)))

recorrer::
Iterar sobre los elementos de un conjunto, realizando una operación similar en cada uno de ellos.
(((recorrido)))

porción::
Una parte de una cadena especificada mediante un rango de índices.
(((porción)))

cadena vacía::
Una cadena sin caracteres y longitud 0, representada por dos comillas.
(((cadena vacía)))

immutable::
La propiedad de una secuencia que hace que a sus elementos no se les pueda asignar nuevos valores.
(((immutable)))

interpolación de cadenas::
El proceso de evaluar una cadena que contiene uno o más marcadores de posición, produciendo un resultado en el que los marcadores de posición se reemplazan con sus valores correspondientes.
(((interpolación de cadenas)))

búsqueda::
Un patrón de recorrido que se detiene cuando encuentra lo que está buscando.
(((búsqueda)))

contador::
Una variable utilizada para contar algo, generalmente inicializada en cero y luego incrementada.
(((contador)))


=== Ejercicios

[[ex08-1]]
==== Ejercicio 8-7

Lea la documentación de las funciones relacionadas con cadenas en https://docs.julialang.org/en/v1/manual/strings/. Es posible que desee probar algunas de ellas para asegurarse de comprender cómo funcionan. +strip+ y +replace+ son particularmente útiles.

La documentación utiliza una sintaxis que puede ser confusa. Por ejemplo, en +search(cadena::AbstractString, caracter::Chars, [comienzo::Integer])+, los corchetes indican argumentos opcionales. Por lo tanto, +cadena+ y +caracter+ son obligatorios, pero +comienzo+ es opcional.
(((búsqueda)))((("función", "Base", "búsqueda", véase "búsqueda")))

[[ex08-2]]
==== Ejercicio 8-8

Hay una función integrada llamada +count+ que es similar a la función en <<looping_and_counting>>. Lea la documentación de esta función y úsela para contar el número de letras +a+ en "banana".
(((conteo)))((("función","Base", "conteo", véase "conteo")))

[[ex08-3]]
==== Ejercicio 8-9

Una porción de cadena puede tomar un tercer índice. El primero especifica el inicio, el tercero el final y el segundo el "tamaño del paso", es decir, el número de espacios entre caracteres sucesivos. Un tamaño de paso de 2 significa cada un caracter; 3 significa cada dos, etc.
(((porción)))

[source,@julia-repl-test]
----
julia> fruta = "banana"
"banana"
julia> fruta[1:2:6]
"bnn"
----

Un tamaño de paso de -1 recorre la palabra hacia la izquierda, por lo que la porción +[end:-1:1]+ genera una cadena invertida.

Use esto para escribir una versión de una línea de código de +espalindroma+ de <<ex06-3>>.
(((espalindromo)))

[[ex08-4]]
==== Exercise 8-10

Las siguientes funciones están _destinadas_ a verificar si una cadena contiene letras minúsculas, pero algunas de ellas son incorrectas. Para cada función, describa qué hace realmente la función (suponiendo que el parámetro es una cadena).

[source,@julia-setup]
----
function cualquierminuscula1(s)
    for c in s
        if islowercase(c)
            return true
        else
            return false
        end
    end
end

function cualquierminuscula2(s)
    for c in s
        if islowercase('c')
            return "true"
        else
            return "false"
        end
    end
end

function cualquierminuscula3(s)
    for c in s
        bandera = islowercase(c)
    end
    flag
end

function cualquierminuscula4(s)
    bandera = false
    for c in s
        bandera = bandera || islowercase(c)
    end
    flag
end

function cualquierminuscula5(s)
    for c in s
        if !islowercase(c)
            return false
        end
    end
    true
end
----

[[ex08-5]]
==== Exercise 8-11

Un cifrado César es una forma simple de cifrado que implica desplazar cada letra un número fijo de lugares. Desplazar una letra significa reemplazarla por otra letra que se encuentra un número fijo de posiciones más adelante en el alfabeto. Es posible desplazarse hasta el principio del abecedario si fuera necesario. De esta manera, con un desplazamiento de 3, +'A'+ es +'D'+, y con un desplazamiento de 1, +'Z'+ es +'A'+ .
(((cifrado César)))

Para desplazar una palabra, desplace cada letra en la misma cantidad. Por ejemplo, con un desplazamiento de 6, +"ABCDEF"+ es +"GHIJKL"+ y con un desplazamiento de -6, +"BCDE"+ es +"VWXY"+. En la película _2001: Una odisea del espacio_, la computadora de la nave se llama HAL, que es IBM desplazada por -1.

Escriba una función llamada +desplazarpalabra+ que tome una cadena y un número entero como parámetros, y devuelva una nueva cadena que contenga las letras de la cadena original desplazadas por la cantidad dada.
(((desplazarpalabra)))((("función","definida por el programador", "desplazarpalabra", véase "desplazarpalabra")))

[TIP]
====
Es posible que desee utilizar la función integrada +Int+, que convierte un carácter en un código numérico, y +Char+, que convierte los códigos numéricos en caracteres. Las letras del alfabeto están codificadas en orden alfabético, por ejemplo:
(((Int)))(((Char)))

[source,@julia-repl-test]
----
julia> Int('c') - Int('a')
2
----

Porque +'c'+ es la tercera letra del alfabeto. Pero cuidado: los códigos numéricos para las letras mayúsculas son diferentes.

[source,@julia-repl-test]
----
julia> Char(Int('A') + 32)
'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)
----
====


Algunos chistes ofensivos en Internet están codificados en ROT13, que es un cifrado César con desplazamiento 13. Si no se ofende fácilmente, encuentre y decodifice algunos de ellos.
