[[chap03]]
== Funciones

En el contexto de la programación, una _función_ es una secuencia de sentencias que realiza un cálculo. Las funciones tienen nombre. Cuando se define una función, se especifica su nombre y secuencia de sentencias. Una vez hecho esto, se puede "llamar" a la función por su nombre.
(((función)))

=== Llamadas a función

Ya hemos visto un ejemplo de una llamada a función:
(((Llamada a función)))

[source,@julia-repl-test]
----
julia> println("¡Hola, mundo!")
¡Hola, Mundo!
----

El nombre de esta función es +println+. La expresión entre paréntesis se llama _argumento_ de la función.
(((argumento)))(((paréntesis)))

Es común decir que una función "toma" un argumento y "devuelve" un resultado. El resultado también se llama _valor de retorno_.
(((valor de retorno)))

Julia proporciona funciones que convierten valores de un tipo a otro. La función +parse+ toma una cadena y la convierte en cualquier tipo de número, si es posible, en caso contrario arroja error:
(((conversión de tipo)))((("función", "Base", "parse", see="parse")))(((ArgumentError)))((("error", "Core", "ArgumentError", see="ArgumentError")))

[source,@julia-repl-test]
----
julia> parse(Int64, "32")
32
julia> parse(Float64, "3.14159")
3.14159
julia> parse(Int64, "Hello")
ERROR: ArgumentError: invalid base 10 digit 'H' in "Hello" (ERROR: ArgumentError: base inválida de 10 dígitos 'H' en "Hola")
----

+trunc+ puede convertir valores de punto flotante a enteros, pero no redondea; sino que trunca:
(((trunc)))((("función", "Base", "trunc", see="trunc")))

[source,@julia-repl-test]
----
julia> trunc(Int64, 3.99999)
3
julia> trunc(Int64, -2.3)
-2
----

+float+ convierte números enteros en números de punto flotante:
(((float)))((("función", "Base", "float", see="float")))

[source,@julia-repl-test]
----
julia> float(32)
32,0
----

Finalmente, +string+ convierte el argumento en una cadena:
(((string)))((("función", "Base", "string", see="string")))

[source,@julia-repl-test]
----
julia> string(32)
"32"
julia> string(3.14159)
"3.14159"
----


=== Funciones matemáticas

En Julia, la mayoría de las funciones matemáticas conocidas están disponibles de manera directa:
(((función matemática)))(((log10)))((("función", "Base", "log10", see="log10")))

[source,julia]
----
proporción = potencia_de_señal/potencia_de_ruido
decibelios = 10*log10(proporción)
----

Este primer ejemplo utiliza +log10+ para calcular la proporción entre señal y ruido en decibelios (suponiendo que se definen +potencia_de_señal+ y +potencia_de_ruido+). También existe +log+, que calcula logaritmo natural.
(((log)))((("función", "Base", "log",see="log")))((("función logaritmo", see="log")))

[source,julia]
----
radianes = 0.7
altura = sin(radianes)
----

Este segundo ejemplo encuentra la razón seno de +radianes+. El nombre de esta variable es una pista de que +sin+ y las otras funciones trigonométricas (+cos+, +tan+, etc.) toman argumentos en radianes. Para convertir grados a radianes, se debe dividir por 180 y multiplicar por latexmath:[\(\pi\)]:
(((sin)))((("función", "Base", "sin", see="sin")))(((función trigonométrica)))

[source,@julia-repl-test]
----
julia> grados=45
45
julia> radianes=grados/180*π
0.7853981633974483
julia> sin(radianes)
0.7071067811865475
----

El valor de la variable +π+ es una aproximación de punto flotante de latexmath:[\(\pi \)], con una precisión de aproximadamente 16 dígitos.
(((Pi)))

Si sabe de trigonometría, puede verificar el resultado anterior comparándolo con la raíz cuadrada de dos dividido por dos:
(((sqrt)))((("función", "Base", "sqrt", see="sqrt")))((("function raíz", see = "sqrt")))

[source,@julia-repl-test]
----
julia> sqrt(2)/ 2
0.7071067811865476
----


=== Composición

Hasta ahora, hemos analizado los elementos de un programa (variables, expresiones y sentencias) de forma aislada, sin mencionar cómo se combinan.
(((composición)))

Una de las características más útiles de los lenguajes de programación es la capacidad de tomar pequeños bloques de código y combinarlos. Por ejemplo, el argumento de una función puede ser cualquier tipo de expresión, incluidos operadores aritméticos:

[source, julia]
----
x = sin(grados/360*2*π)
----

E incluso llamadas a funciones:
(((exp)))((("función", "Base", "exp", see="exp"))) ((("función exponencial", see="exp")))

[source, julia]
----
x = exp(log(x + 1))
----

Casi en cualquier lugar donde se pueda poner un valor, se puede poner una expresión arbitraria, con una excepción: el lado izquierdo de una sentencia de asignación debe ser un nombre de variable. Cualquier otra expresión en el lado izquierdo genera un error de sintaxis (veremos excepciones a esta regla más adelante).
(((error de sintaxis)))

[source,@julia-eval chap03]
----
horas = 2;
----

[source,@julia-repl-test chap03]
----
julia> minutos = horas * 60 # derecha
120
julia> horas * 60 = minutos # malo!
ERROR: syntax: "60" is not a valid function argument name (ERROR: sintaxis: "60" no es un nombre de argumento de función válido)
----

=== Agregar nuevas funciones

Hasta ahora, solo hemos usado las funciones que vienen con Julia, pero también es posible agregar nuevas funciones. Una _definición de función_ especifica el nombre de una nueva función y la secuencia de sentencias que se ejecutan cuando se llama a la función. Aquí hay un ejemplo:
(((función)))(((definición de función)))(((función definida por el programador)))(((imprimirletras)))((("función", "definido por el programador", "imprimirletras", see="imprimirletras")))

[source,@julia-setup chap03]
----
function imprimirletras()
    println("Jueguemos en el bosque")
    println("mientras el lobo no está.")
end
----

+function+ es una palabra reservada que indica que esta es una definición de función. El nombre de la función es +imprimirletras+. Las reglas para los nombres de funciones son las mismas que para los nombres de variables: pueden contener casi todos los caracteres Unicode (consulte <<caracteres>>), pero el primer carácter no puede ser un número. No puede usar una palabra clave como nombre de una función, y debe evitar tener una variable y una función con el mismo nombre.
((("palabra clave", "función", see="función")))(((argumento)))(((carácter Unicode)))

Los paréntesis vacíos después del nombre indican que esta función no toma ningún argumento.
(((paréntesis, vacíos)))

La primera línea de una definición de función se llama _encabezado_; el resto se llama _cuerpo_. El cuerpo termina con la palabra reservada +end+ y puede contener todas las sentencias que desee. Para facilitar la lectura, el cuerpo de la función debería tener sangría.
(((encabezado)))(((cuerpo)))(((end)))((("palabra reservada", "final", see="final")))(((sangría)))

Las comillas deben ser "comillas simples", generalmente ubicadas junto a la tecla Enter en el teclado. Las "comillas inglesas dobles", como las de esta oración, no son válidas en Julia.
(((comillas)))

Si escribe una definición de función en modo interactivo, el REPL inserta una sangría para informarle que la definición no está completa:

[source,jlcon]
----
julia> function imprimirletras()
        println("Jueguemos en el bosque")

----

Para finalizar la función, debe escribir +end+.

La sintaxis para llamar a la nueva función es la misma que para las funciones integradas en Julia:

[source,@julia-repl-test chap03]
----
julia> imprimirletras()
Jueguemos en el bosque
mientras el lobo no está.
----

Una vez que haya definido una función, puede usarla dentro de otra función. Por ejemplo, para repetir el estribillo anterior, podríamos escribir una función llamada +repetirletras+:
(((repetirletras)))((("función", "definido por el programador", "repetirletras", see="repetirletras")))

[source,@julia-setup chap03]
----
función repetirletras()
    imprimirletras()
    imprimirletras()
end
----

Y luego llamammos a +repetirletras+:

[fuente, @ julia-repl-test chap03]
----
julia> repeatlyrics ()
Jueguemos en el bosque
mientras el lobo no está.
Jueguemos en el bosque
mientras el lobo no está.
----

Aunque sabemos que la canción no es así.


=== Definiciones y usos

Al reunir los fragmentos de código de la sección anterior, todo el programa se ve así:

[source,julia]
----
function imprimirletras()
    println("Jueguemos en el bosque")
    println("mientras el lobo no está.")
end

función repetirletras()
    imprimirletras()
    imprimirletras()
end

repetirletras()
----

Este programa contiene dos definiciones de funciones: +imprimirletras+ y +repetirletras+. Las definiciones de función se ejecutan al igual que otras sentencias, y con ello se crean objetos de función. Las sentencias dentro de la función no se ejecutan hasta que se llama a la función, y la definición de la función no genera output.

Como es de esperar, debe crear una función antes de poder ejecutarla. En otras palabras, la definición de la función tiene que ejecutarse antes de que se llame a la función.

===== Ejercicio 3-1

Mueva la última línea de este programa a la parte superior, de modo que la llamada a la función aparezca antes de las definiciones. Ejecute el programa y vea qué mensaje de error obtiene.

Ahora mueva la llamada de función hacia abajo y mueva la definición de +imprimirletras+ después de la definición de +repetirletras+. ¿Qué sucede cuando ejecutas este programa?


=== Flujo de ejecución

Para asegurar de que una función sea definida antes de su primer uso, debe conocer el orden en que se ejecutan las instrucciones, lo que se denomina _flujo de ejecución_.
(((flujo de ejecución)))

La ejecución siempre comienza con la primera sentencia del programa. Las sentencias se ejecutan de una en una, de arriba hacia abajo.

Las definiciones de funciones no alteran el flujo de ejecución del programa, pero recuerde que las sentencias dentro de la función no se ejecutan hasta que se llama a la función.

Una llamada de función es como un desvío en el flujo de ejecución. En lugar de pasar a la siguiente sentencia, el flujo salta al cuerpo de la función, ejecuta las sentencias que están allí y luego regresa para continuar el código donde lo dejó.

Eso suena bastante simple, hasta que recuerdas que una función puede llamar a otra. Mientras está en el medio de una función, el programa podría tener que ejecutar las declaraciones en otra función. Luego, mientras ejecuta esa nueva función, ¡el programa podría tener que ejecutar otra función más!

Afortunadamente, Julia es buena para llevar registros de dónde está, por lo que cada vez que se completa una función, el programa retoma donde lo dejó en la función que la llamó. Cuando llega al final del programa, finaliza.

En resumen, cuando lee un programa, no siempre debes leer de arriba a abajo. A veces tiene más sentido seguir el flujo de ejecución.


=== Parámetros y argumentos

Algunas de las funciones que hemos visto requieren argumentos. Por ejemplo, cuando llamas + sin + pasas un número como argumento. Algunas funciones toman más de un argumento: + parse + toma dos, un tipo de número y una cadena.
(((parámetro))) (((argumento))) (((analizar))) (((sin)))

Dentro de la función, los argumentos se asignan a variables llamadas _parameters_. Aquí hay una definición para una función que toma un argumento:
(((printtwice))) ((("función", "definido por el programador", "printtwice", ver = "printtwice")))

[fuente, @ julia-setup chap03]
----
función printtwice (bruce)
    println (bruce)
    println (bruce)
final
----

Esta función asigna el argumento a un parámetro llamado + bruce +. Cuando se llama a la función, imprime el valor del parámetro (cualquiera que sea) dos veces.

Esta función funciona con cualquier valor que se pueda imprimir.

[fuente, @ julia-repl-test chap03]
----
julia> printtwice ("Spam")
Correo no deseado
Correo no deseado
julia> imprenta (42)
42
42
julia> imprenta (π)
π = 3.1415926535897 ...
π = 3.1415926535897 ...
----

Las mismas reglas de composición que se aplican a las funciones integradas también se aplican a las funciones definidas por el programador, por lo que podemos usar cualquier tipo de expresión como argumento para + printtwice +:
(((composición))) (((función definida por el programador)))

[fuente, @ julia-repl-test chap03]
----
julia> printtwice ("Spam" ^ 4)
Spam Spam Spam Spam
Spam Spam Spam Spam
julia> printtwice (cos (π))
-1.0
-1.0
----

El argumento se evalúa antes de llamar a la función, por lo que en los ejemplos las expresiones + "Spam" ^ 4 + y + cos (π) + solo se evalúan una vez.
(((argumento))) (((cos))) ((("function", "Base", "cos", see = "cos")))

También puede usar una variable como argumento:

[fuente, @ julia-repl-test chap03]
----
julia> michael = "Eric, la mitad de una abeja".
"Eric, la mitad de una abeja".
julia> imprenta (michael)
Eric, la mitad de una abeja.
Eric, la mitad de una abeja.
----

El nombre de la variable que pasamos como argumento (+ michael +) no tiene nada que ver con el nombre del parámetro (+ bruce +). No importa cómo se llamó el valor en casa (en la persona que llama); aquí en + printtwice +, llamamos a todos + bruce +.


=== Las variables y los parámetros son locales

Cuando crea una variable dentro de una función, es _local_, lo que significa que solo existe dentro de la función. Por ejemplo:
(((variable local))) (((variable, local))) (((cattwice))) ((("función", "definido por el programador", "cattwice", see = "cattwice")))

[fuente, @ julia-setup chap03]
----
función cattwice (parte1, parte2)
    concat = parte1 * parte2
    imprenta (concat)
final
----

Esta función toma dos argumentos, los concatena e imprime el resultado dos veces. Aquí hay un ejemplo que lo usa:
(((concatenar))) (((repetición)))

[fuente, @ julia-repl-test chap03]
----
julia> line1 = "Tingdle de Bing"
"Bing tiddle"
julia> line2 = "tiddle bang".
"tiddle bang".
julia> cattwice (línea1, línea2)
Bing tiddle tiddle bang.
Bing tiddle tiddle bang.
----

Cuando + cattwice + termina, la variable + concat + se destruye. Si intentamos imprimirlo, obtenemos una excepción:
(((error en tiempo de ejecución))) (((UndefVarError))) ((("error", "Core", "UndefVarError", see = "UndefVarError")))

[fuente, @ julia-repl-test chap03]
----
julia> println (concat)
ERROR: UndefVarError: concat no definido
----

Los parámetros también son locales. Por ejemplo, fuera + printtwice +, no hay tal cosa como + bruce +.
(((parámetro)))


[[stack_diagrams]]
=== Diagramas de pila

Para realizar un seguimiento de las variables que se pueden usar y dónde, a veces es útil dibujar un _ diagrama de pila_. Al igual que los diagramas de estado, los diagramas de pila muestran el valor de cada variable, pero también muestran la función a la que pertenece cada variable.
(((diagrama de pila))) ((("diagrama", "pila", ver = "diagrama de pila")))

Cada función está representada por un _frame_. Un marco es un cuadro con el nombre de una función al lado y los parámetros y variables de la función dentro de él. El diagrama de pila para el ejemplo anterior se muestra en <<fig03-1>>.
(((marco)))

[[fig03-1]]
Diagrama de pila
imagen :: images / fig31.svg []

Los marcos están dispuestos en una pila que indica qué función se llama a cuál, y así sucesivamente. En este ejemplo, + printtwice + fue llamado por + cattwice +, y + cattwice + fue llamado por + Main +, que es un nombre especial para el marco superior. Cuando crea una variable fuera de cualquier función, pertenece a + Main +.

Cada parámetro se refiere al mismo valor que su argumento correspondiente. Entonces, + part1 + tiene el mismo valor que + line1 +, + part2 + tiene el mismo valor que + line2 +, y + bruce + tiene el mismo valor que + concat +.

Si se produce un error durante una llamada a la función, Julia imprime el nombre de la función, el nombre de la función que la llamó y el nombre de la función que llamó a _that_, todo el camino de regreso a + Main +.
(((Principal)))

Por ejemplo, si intenta acceder a + concat + desde + printtwice +, obtendrá un + UndefVarError +:
(((UndefVarError)))

----
ERROR: UndefVarError: concat no definido
Stacktrace:
 [1] imprimir dos veces en ./REPL[1font>:2 [en línea]
 [2] cattwice (:: String, :: String) en ./REPL[2font>:3
----

Esta lista de funciones se llama _stacktrace_. Le indica en qué archivo de programa se produjo el error, en qué línea y qué funciones se estaban ejecutando en ese momento. También muestra la línea de código que causó el error.
(((stacktrace)))

El orden de las funciones en el stacktrace es el inverso del orden de los cuadros en el diagrama de stack. La función que se está ejecutando actualmente está en la parte superior.


=== Funciones fructíferas y funciones nulas

Algunas de las funciones que hemos utilizado, como las funciones matemáticas, devuelven resultados; por falta de un nombre mejor, los llamo funciones fructíferas. Otras funciones, como + printtwice +, realizan una acción pero no devuelven un valor. Se llaman _ funciones vacías_.
(((función fructífera))) (((función nula)))

Cuando llamas a una función fructífera, casi siempre quieres hacer algo con el resultado; por ejemplo, puede asignarlo a una variable o usarlo como parte de una expresión:

[fuente, julia]
----
x = cos (radianes)
dorado = (sqrt (5) + 1) / 2
----

Cuando llama a una función en modo interactivo, Julia muestra el resultado:
(((modo interactivo)))

[fuente, @ julia-repl-test]
----
julia> sqrt (5)
2.23606797749979
----

Pero en un script, si llama a una función fructífera por sí sola, ¡el valor de retorno se pierde para siempre!
(((modo script)))

[fuente, @ julia-run]
----
sqrt (5)
----

Este script calcula la raíz cuadrada de 5, pero como no almacena ni muestra el resultado, no es muy útil.

Las funciones nulas pueden mostrar algo en la pantalla o tener algún otro efecto, pero no tienen un valor de retorno. Si asigna el resultado a una variable, obtendrá un valor especial llamado + nada +.
(((nada)))

[fuente, @ julia-repl-test chap03]
----
julia> resultado = printtwice ("Bing")
Bing
Bing
julia> show (resultado)
nada
----

Para imprimir el valor + nothing +, debe usar la función + show + que es como + print + pero puede manejar el valor + nothing +.
(((show))) ((("function", "Base", "show", see = "show")))

El valor + nada + no es lo mismo que la cadena + "nada" +. Es un valor especial que tiene su propio tipo:
(((Nothing))) ((("type", "Base", "Nothing", see = "Nothing")))

[fuente, @ julia-repl-test]
----
julia> typeof (nada)
Nada
----

Las funciones que hemos escrito hasta ahora son nulas. Comenzaremos a escribir funciones fructíferas en unos pocos capítulos.


=== ¿Por qué funciones?

Puede que no esté claro por qué vale la pena dividir un programa en funciones. Hay varias razones:

* Crear una nueva función le brinda la oportunidad de nombrar un grupo de declaraciones, lo que hace que su programa sea más fácil de leer y depurar.

* Las funciones pueden hacer que un programa sea más pequeño al eliminar el código repetitivo. Más tarde, si realiza un cambio, solo tiene que hacerlo en un solo lugar.

* Dividir un programa largo en funciones le permite depurar las partes de una en una y luego ensamblarlas en un todo funcional.

* Las funciones bien diseñadas a menudo son útiles para muchos programas. Una vez que escribe y depura uno, puede reutilizarlo.

* En Julia, las funciones pueden mejorar mucho el rendimiento.


=== Depuración

Una de las habilidades más importantes que adquirirás es la depuración. Aunque puede ser frustrante, la depuración es una de las partes más intelectualmente ricas, desafiantes e interesantes de la programación.
(((depuración)))

De alguna manera, la depuración es como un trabajo de detective. Te enfrentas a pistas y tienes que inferir los procesos y eventos que llevaron a los resultados que ves.

La depuración también es como una ciencia experimental. Una vez que tenga una idea de lo que va mal, modifique su programa e intente nuevamente. Si su hipótesis era correcta, puede predecir el resultado de la modificación y dar un paso más hacia un programa de trabajo. Si su hipótesis era incorrecta, tiene que encontrar una nueva. Como Sherlock Holmes señaló:

[cita, A. Conan Doyle, El signo de los cuatro]
____
Cuando haya eliminado lo imposible, lo que queda, por improbable que sea, debe ser la verdad.
____
(((depuración experimental))) (((Holmes, Sherlock))) (((Doyle, Arthur Conan)))

Para algunas personas, la programación y la depuración son lo mismo. Es decir, la programación es el proceso de depurar gradualmente un programa hasta que haga lo que desea. La idea es que debe comenzar con un programa de trabajo y hacer pequeñas modificaciones, depurándolas a medida que avanza.

Por ejemplo, Linux es un sistema operativo que contiene millones de líneas de código, pero comenzó como un programa simple que Linus Torvalds usó para explorar el chip Intel 80386. Según Larry Greenfield, "Uno de los proyectos anteriores de Linus fue un programa que cambiaría entre imprimir" AAAA "y" BBBB ". Esto luego evolucionó a Linux ". (_The Linux Users'’ Guide_ Beta Version 1).
(((Linux))) (((Torvalds, Linus)))


=== Glosario

función::
Una secuencia, con nombre, de sentencias que realiza alguna operación útil. Las funciones pueden tomar o no argumentos y pueden producir o no un resultado.
(((función)))

definición de función::
Una sentencia que crea una nueva función, especificando su nombre, parámetros y las sentencias que contiene.
(((definición de función)))

objeto de función::
Un valor creado por una definición de función. El nombre de la función es una variable que se refiere a un objeto de función.
(((objeto de función)))

encabezado::
La primera línea de una definición de función.
(((encabezado)))

cuerpo::
La secuencia de sentencias dentro de una definición de función.
(((cuerpo)))

parámetro::
Un nombre usado dentro de una función para referirse al valor pasado como argumento.
(((parámetro)))

Llamada a función::
Una sentencia que ejecuta una función. Consiste en el nombre de la función seguido de una lista de argumentos entre paréntesis.
(((Llamada a función)))

argumento::
Un valor proporcionado a una función cuando se llama a la función. Este valor se asigna al parámetro correspondiente en la función.
(((argumento)))

variable local::
Una variable definida dentro de una función. Una variable local solo puede usarse dentro de su función.
(((variable local)))

valor de retorno::
El resultado de una función. Si se utiliza una llamada a función como una expresión, el valor de retorno es el valor de la expresión.
(((valor de retorno)))

función fructífera::
Una función que devuelve un valor.
(((función fructífera)))

función vacía::
Una función que siempre devuelve +nada+.
(((función nula)))

+nada+::
Un valor especial devuelto por las funciones nulas.
(((nada)))

composición::
Usar una expresión como parte de una expresión más grande, o una sentencia como parte de una sentencia más grande.
(((composición)))

flujo de ejecución::
El orden en que las sentencias se ejecutan.
(((flujo de ejecución)))

diagrama de pila ::
Una representación gráfica de una pila de funciones, sus variables y los valores a los que se refieren.
(((diagrama de pila)))

marco::
Un cuadro en un diagrama de pila que representa una llamada de función. Contiene las variables locales y los parámetros de la función.
(((marco)))

stacktrace ::
Una lista de las funciones que se están ejecutando, impresas cuando ocurre una excepción.
(((stacktrace)))


=== Ejercicios

[PROPINA]
====
Estos ejercicios deben hacerse usando solo las declaraciones y otras características que hemos aprendido hasta ahora.
====

[[ex03-1]]
===== Ejercicio 3-2

Escriba una función llamada + rightjustify + que tome una cadena llamada + s + como parámetro e imprima la cadena con suficientes espacios iniciales para que la última letra de la cadena se encuentre en la columna 70 de la pantalla.
(((rightjustify))) ((("función", "definido por el programador", "rightjustify", ver = "rightjustify)))

[fuente, @ julia-eval chap03-ex]
----
usando ThinkJulia
----

[fuente, @ julia-repl chap03-ex]
----
rightjustify ("monty")
----

[PROPINA]
====
Use la concatenación y repetición de cuerdas. Además, Julia proporciona una función incorporada llamada + length + que devuelve la longitud de una cadena, por lo que el valor de + length ("monty") + es 5.
(((length))) ((("function", "Base", "length", see = "length)))
====

[[ex03-2]]
===== Ejercicio 3-3

Un objeto de función es un valor que puede asignar a una variable o pasar como argumento. Por ejemplo, + dotwice + es una función que toma un objeto de función como argumento y lo llama dos veces:
(((objeto de función))) (((dotwice))) ((("función", "definido por el programador", "dotwice", ver = "dotwice")))

[fuente, julia]
----
función dotwice (f)
    F()
    F()
final
----

Aquí hay un ejemplo que usa + dotwice + para llamar a una función llamada + printspam + dos veces.
(((printspam))) ((("función", "definido por el programador", "printspam", ver = "printspam")))

[fuente, julia]
----
función printspam ()
    println ("spam")
final

dotwice (estampado)
----

. Escriba este ejemplo en un script y pruébelo.

. Modifique + dotwice + para que tome dos argumentos, un objeto de función y un valor, y llame a la función dos veces, pasando el valor como argumento.

. Copie la definición de + printtwice + de antes en este capítulo a su secuencia de comandos.

. Use la versión modificada de + dotwice + para llamar a + printtwice + dos veces, pasando + "spam" + como argumento.

. Defina una nueva función llamada + dofour + que toma un objeto de función y un valor y llama a la función cuatro veces, pasando el valor como parámetro. Debe haber solo dos declaraciones en el cuerpo de esta función, no cuatro.
(((dofour))) ((("función", "definido por el programador", "dofour", ver = "dofour")))

[[ex03-3]]
===== Ejercicio 3-4

. Escriba una función + printgrid + que dibuje una cuadrícula como la siguiente:
(((printgrid))) ((("función", "definida por el programador", "printgrid", ver = "printgrid")))
+
[fuente, @ julia-repl-test chap03-ex]
----
julia> printgrid ()
+ - - - - + - - - - +
El | El | El |
El | El | El |
El | El | El |
El | El | El |
+ - - - - + - - - - +
El | El | El |
El | El | El |
El | El | El |
El | El | El |
+ - - - - + - - - - +
----

. Escriba una función que dibuje una cuadrícula similar con cuatro filas y cuatro columnas.

Crédito: Este ejercicio se basa en un ejercicio en Oualline, _Programación práctica C_, tercera edición, O’Reilly Media, 1997.

[PROPINA]
====
Para imprimir más de un valor en una línea, puede imprimir una secuencia de valores separados por comas:

[fuente, julia]
----
println ("+", "-")
----

La función + imprimir + no avanza a la siguiente línea:

[fuente, julia]
----
imprimir ("+")
println ("-")
----

El resultado de estas declaraciones es + pass: ["+ -"] + en la misma línea. El resultado de la siguiente declaración de impresión comenzaría en la siguiente línea.
====
(((println))) (((print))) ((("function", "Base", "print", see = "print")))
